runtime: python37
instance_class: F2
entrypoint: gunicorn -b :8080 -w 2 main:app

env_variables:
          BUCKET_NAME: "covid19-seir"
          handlers:
                  # Matches requests to /images/... to files in static/images/...
                  # - url: /images
                  #   static_dir: static/images
                  #
                  #   - url: /.*
                  #     secure: always
                  #       redirect_http_response_code: 301
                  #         script: auto
